# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
  #---------------------------
  development:
    adapter: postgresql
    encoding: unicode
    host: localhost
    port: 5432
    database: wicoding
    pool: 5
    username: WSM
    password: 

  #---------------------------

  production:
    url: <%= ENV['DATABASE_URL'] %>
